version: '3'
services:

  postgres:
    image: postgres:9.6-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${CONF_DATA_SOURCE_USERNAME}
      POSTGRES_PASSWORD: ${CONF_DATA_SOURCE_PASSWORD}
      POSTGRES_DB: ${CONF_DATA_SOURCE_DB}
volumes:
  db_data: {}